# Generated by Django 4.2.7 on 2025-08-27 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Database",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=100)),
                (
                    "default_view",
                    models.CharField(
                        choices=[
                            ("table", "Table"),
                            ("board", "Board"),
                            ("list", "List"),
                            ("calendar", "Calendar"),
                            ("gallery", "Gallery"),
                            ("timeline", "Timeline"),
                        ],
                        default="table",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_databases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="databases",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DatabaseProperty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("select", "Select"),
                            ("multi_select", "Multi-select"),
                            ("date", "Date"),
                            ("person", "Person"),
                            ("files", "Files & media"),
                            ("checkbox", "Checkbox"),
                            ("url", "URL"),
                            ("email", "Email"),
                            ("phone", "Phone number"),
                            ("formula", "Formula"),
                            ("relation", "Relation"),
                            ("rollup", "Rollup"),
                            ("created_time", "Created time"),
                            ("created_by", "Created by"),
                            ("last_edited_time", "Last edited time"),
                            ("last_edited_by", "Last edited by"),
                        ],
                        max_length=20,
                    ),
                ),
                ("config", models.JSONField(default=dict)),
                ("position", models.FloatField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "database",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="databases.database",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "unique_together": {("database", "name")},
            },
        ),
        migrations.CreateModel(
            name="DatabaseRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("properties", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "database",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="databases.database",
                    ),
                ),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edited_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="SelectOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("color", models.CharField(default="#6B7280", max_length=7)),
                ("position", models.FloatField(default=0)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="databases.databaseproperty",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "unique_together": {("property", "name")},
            },
        ),
        migrations.CreateModel(
            name="DatabaseView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("table", "Table"),
                            ("board", "Board"),
                            ("list", "List"),
                            ("calendar", "Calendar"),
                            ("gallery", "Gallery"),
                            ("timeline", "Timeline"),
                        ],
                        max_length=10,
                    ),
                ),
                ("filters", models.JSONField(default=list)),
                ("sorts", models.JSONField(default=list)),
                ("groups", models.JSONField(default=list)),
                ("properties", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "database",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="databases.database",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("database", "name")},
            },
        ),
        migrations.CreateModel(
            name="DatabaseRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_database",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relations",
                        to="databases.database",
                    ),
                ),
                (
                    "from_property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relations",
                        to="databases.databaseproperty",
                    ),
                ),
                (
                    "to_database",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relations",
                        to="databases.database",
                    ),
                ),
                (
                    "to_property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relations",
                        to="databases.databaseproperty",
                    ),
                ),
            ],
            options={
                "unique_together": {("from_database", "to_database", "from_property")},
            },
        ),
    ]
