# Generated by Django 4.2.7 on 2025-08-31 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0001_initial"),
        ("notes", "0001_initial"),
        ("databases", "0002_databaserecordrevision_databasecomment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("collaboration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollaborationComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "database",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaboration_comments",
                        to="databases.database",
                    ),
                ),
                (
                    "database_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaboration_comments",
                        to="databases.databaserecord",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaboration_comments",
                        to="notes.page",
                    ),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="collaboration.collaborationcomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaboration_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="activesession",
            name="last_activity",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="activesession",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workspaces.workspace",
            ),
        ),
        migrations.CreateModel(
            name="CollaborationReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[
                            ("like", "👍"),
                            ("love", "❤️"),
                            ("laugh", "😂"),
                            ("wow", "😮"),
                            ("sad", "😢"),
                            ("angry", "😠"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="collaboration.collaborationcomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaboration_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["comment", "reaction_type"],
                        name="collaborati_comment_c12934_idx",
                    ),
                    models.Index(
                        fields=["user", "reaction_type"],
                        name="collaborati_user_id_bb5b93_idx",
                    ),
                ],
                "unique_together": {("user", "comment", "reaction_type")},
            },
        ),
        migrations.AddIndex(
            model_name="collaborationcomment",
            index=models.Index(
                fields=["workspace", "created_at"],
                name="collaborati_workspa_dbd4ca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="collaborationcomment",
            index=models.Index(
                fields=["page", "created_at"], name="collaborati_page_id_7969ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collaborationcomment",
            index=models.Index(
                fields=["database", "created_at"], name="collaborati_databas_3d62ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collaborationcomment",
            index=models.Index(
                fields=["database_record", "created_at"],
                name="collaborati_databas_11f7f9_idx",
            ),
        ),
    ]
